services:
  node-docker:
    image: selenium/node-docker:4.16.1-20231219
    volumes:
      - ./assets:/opt/selenium/assets
      - ./GridConfig/config.toml:/opt/bin/config.toml
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - my_network

  selenium-hub:
    image: selenium/hub:4.16.1-20231219
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - my_network

networks: 
   my_network:
