name: .NET 6.0
on:
  push:

jobs:
  build:
    name: Build & Test
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - uses:  ./
      with:
        test-assembly-path: ReplayProjectTest/bin/Release/net6.0
        test-assembly-dll: ReplayProjectTest.dll
        output-html: LivingDoc.html
        framework: net6.0
    - name: Deploy Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports      
